language: rust
cache:
  cargo: true
  timeout: 1000

rust:
  - nightly

script:
  - rustup target install wasm32-unknown-unknown
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
  - cargo doc --verbose --workspace --document-private-items
  #- cargo fmt --all -- --check

notifications:
  email:
    on_success: never
    on_failure: never
