language: rust
cache:
  cargo: true
  timeout: 1000

rust:
  - nightly

dist: xenial
addons:
  apt:
    sources:
      - llvm-toolchain-xenial-8
    packages:
      - clang-8

env:
  - CC=clang-8
  - CXX=clang++-8

script:
  - rustup target install wasm32-unknown-unknown
  - rustup target install wasm32-wasi
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
  - cargo doc --verbose --workspace --document-private-items
  #- cargo fmt --all -- --check

notifications:
  email:
    on_success: never
    on_failure: never
