[workspace]
members = [
    "core",
    "kernel",
    "interfaces/syscalls",
    "modules/ipfs",
    "modules/preloaded",
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
