[package]
name = "ipfs"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
futures-preview = { version = "0.3.0-alpha.18", features = ["compat", "io-compat"] }
futures01 = { package = "futures", version = "0.1" }
interface = { path = "../../interfaces/interface" }
libp2p-core = { git = "https://github.com/tomaka/libp2p-rs", branch = "wasi" }
libp2p-kad = { git = "https://github.com/tomaka/libp2p-rs", branch = "wasi" }
libp2p-mplex = { git = "https://github.com/tomaka/libp2p-rs", branch = "wasi" }
#libp2p-secio = { git = "https://github.com/tomaka/libp2p-rs", branch = "wasi" }
libp2p-plaintext = { git = "https://github.com/tomaka/libp2p-rs", branch = "wasi" }
libp2p-swarm = { git = "https://github.com/tomaka/libp2p-rs", branch = "wasi" }
log = "0.4"
syscalls = { path = "../../interfaces/syscalls" }
tcp = { path = "../../interfaces/tcp" }
threads = { path = "../../interfaces/threads" }
