[package]
name = "ipfs"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
futures-preview = { version = "0.3.0-alpha.18", features = ["compat"] }
libp2p = "0.12.0"
syscalls = { path = "../../interfaces/syscalls" }
tcp = { path = "../../interfaces/tcp" }
