[package]
name = "redshirt-tap-hosted"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3.1"
redshirt-network-interface = { path = "../../interfaces/network" }
redshirt-syscalls-interface = { path = "../../interfaces/syscalls" }
parity-scale-codec = "1.0.5"
rand = "0.7"
tun-tap = { version = "0.1.2", default-features = false }
