[package]
name = "kernel"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "../core" }
futures-preview = "0.3.0-alpha.18"
