[package]
name = "kernel-core"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
bimap = "0.4.0"
bs58 = { version = "0.2.5", default-features = false }
err-derive = "0.1.5"
futures-preview = { version = "0.3.0-alpha.18", default-features = false }      # TODO: necessary?
hashbrown = "0.6.0"
smallvec = { version = "0.6.10", default-features = false }
sha2 = "0.8.0"
wabt = "0.9.1"
wasmi = { git = "https://github.com/tomaka/wasmi", branch = "moo", default-features = false, features = ["core"] }
#wasmi = { version = "0.5.1", default-features = false, features = ["core"] }       # TODO: https://github.com/paritytech/wasmi/pull/210
