[package]
name = "core"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"

[dependencies]
bimap = "0.4.0"
bs58 = { version = "0.2.5", default-features = false }
hashbrown = "0.6.0"
sha2 = "0.8.0"
wabt = "0.9.1"
wasmi = { version = "0.5.1", default-features = false, features = ["core"] }
