[package]
name = "preloaded"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[workspace]

[dependencies]
dlmalloc = { version = "0.1.3", features = ["global"] }
tiny-keccak = "1.5"

[profile.release]
panic = "abort"
