[package]
name = "redshirt-webgpu-hosted"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3.0"
parking_lot = "0.10.0"
redshirt-core = { path = "../../core" }
redshirt-interface-interface = { path = "../../interfaces/interface" }
redshirt-webgpu-interface = { path = "../../interfaces/webgpu" }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "1529a88fd9f23cd1921b30c58d06ba2d8dc46ce7" }
